### ISSUE TITLE
Blockage models parameters 

### ISSUE THREAD

**Issue by Ooussamaa** [DTUWindEnergy/PyWake#10]
Hello,

I am trying to model Blockage effects on Pywake, I can't find the parameters to play on for each model like it's the case for wake: NOJ(k) and Bastankhah  (k & ceps)... . I only know that VD model includs "sct" but I still need the parameters of VortexCylindet ans SS.
I can't find a session on Pywake documentation that discuss this.
Please push me to the right direction !.

Thank you 

Best regards 
Oussama 
(I did not use The traker link coz I still waiting fo mail connexion informations to be approuved)

**Comment by madsmpedersen** [comment]
The code is here: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/blob/master/py_wake/deficit_models/vortexcylinder.py#L10
I am not sure which parameters you want to play with. The current implementation does not take any tuning parameters, so you may need to implement that youself
