### ISSUE TITLE
Calculation of AEP of an individual turbine in a site

### ISSUE THREAD

**Issue by AzathaReddy** [DTUWindEnergy/PyWake#12]
Hello PyWake team, I am trying to calculate the AEP using jensen wake model. I created a site using xrsite that contains 5 turbines which has different 12 - sector wind distributions and varying wind speeds.  I am searching for a method that allows me to calculate the AEP of the individual turbine in the wind direction of lets say 270°. The result of the simulation for 5 different wind distribution is not realistic because it is 5 times the  actual AEP. If there is a way that I can get the AEP of an individual turbine in a specific direction so that I can calculate the sum. I want to use this for maximization of energy production objective function for pso algorithm.

**Comment by madsmpedersen** [comment]
Please take a look at the quickstart: https://topfarm.pages.windenergy.dtu.dk/PyWake/notebooks/Quickstart.html
The `simulationResult.aep()` method returns a xarray dataarray with AEP as a function of wt, wd and ws that you can query with 
```
aep = simulationResult.aep()
aep.sel(wt=0).sum()
```

Please use the issue tracker on https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues
