### ISSUE TITLE
SLSQP optimise

### ISSUE THREAD

**Issue by MichaelRichardThomson** [DTUWindEnergy/PyWake#2]
Hi, after updating to version 2.4 when optimizing with SLSQP I get the ''AttributeError: 'TurboNOJDeficit' object has no attribute 'dAEPdxy''' 

Is there a way to fix this? 

Kind regards, 

Michael

**Comment by madsmpedersen** [comment]
Hi Michael
Please use the issue tracker on https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues, as this github repos is just a mirror for integration with zenodo

`dAEPdxy` has been replaced with `aep_gradients`, see example here: https://topfarm.pages.windenergy.dtu.dk/PyWake/notebooks/Optimization.html#AEP-gradients-with-respect-to-(x,y)-or-(xy)

Kind regards
Mads

**Comment by MichaelRichardThomson** [comment]
Hi Mads, 

Thanks for the reply and links! As my request for gitlab is approved I will use the issue tracker on gitlab from now on. 

Kind regards, 

Michael
