### ISSUE TITLE
Threads and CPU usage

### ISSUE THREAD

**Issue by viktorsmari** [DTUWindEnergy/PyWake#3]
I have a Webapp that runs Python scripts to run PyWake and I notice that my 6 CPU server only uses 1 thread.

Does PyWake use multiple threads?

**Comment by madsmpedersen** [comment]
Please use the issue tracker on https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues, as this github repos is just a mirror for integration with zenodo

There is a n_cpu argument for for windFarmModel.__call__ and windFarmModel.aep which defaults to 1. Setting it to 6 or None (all available cpus) will result in parallel execution
