### ISSUE TITLE
"import py_wake" problem

### ISSUE THREAD

**Issue by hedonicas** [DTUWindEnergy/PyWake#6]
`import py_wake` results with:

`ModuleNotFoundError: No module named 'xarray.plot.plot'`

Can you please help? If there is problem with installed packages, please share `"requirements.txt"` with me. Thanks.

**Comment by madsmpedersen** [comment]
Please use the issue tracker on https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues, as this github repos is just a mirror for integration with zenodo

The requirements are listed here: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/blob/master/setup.py#L55
BR
Mads

**Comment by madsmpedersen** [comment]
The problem was an update of the xarray structure. I have merged a fix

**Comment by hedonicas** [comment]
Thank you very much!
