### ISSUE TITLE
import Py_wake error

### ISSUE THREAD

**Issue by Kaplan3458** [DTUWindEnergy/PyWake#7]
`import py_wake error` : 
Hello sir, when I try to run your code in my computer I get "ModuleNotFoundError: No module named 'xarray.plot.plot'" I am sure about that ı have already ınstalled xarray. I tired everything to solve this problem but unfortunately I did not. Could you help me about this problem? 
Best regards. 
Research Assistant B. K.

**Comment by madsmpedersen** [comment]
Please use the issue tracker on https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues

xarray.plot.plot is defined here: https://github.com/pydata/xarray/blob/main/xarray/plot/__init__.py#L24
so I suspect that xarray is not installed in the environment you are using for pywake

**Comment by Kaplan3458** [comment]
Dear sir, I tried to join GitLab but, ı saw this message. I thought you
blocked my e-mail address. My username is bugra and my e-mail address is
***@***.***  Thank you for helping. I will wait for your messages.

Best Regards.
Bugra Kaplan



madsmpedersen ***@***.***>, 14 Kas 2022 Pzt, 13:55 tarihinde
şunu yazdı:

**Comment by madsmpedersen** [comment]
The problem was an update of the xarray structure. I have merged a fix
