### ISSUE TITLE
Time-dependent flow maps

### ISSUE THREAD

**Issue by ArHelms** [DTUWindEnergy/PyWake#8]
Hi,

as described in the tutorial (https://topfarm.pages.windenergy.dtu.dk/PyWake/notebooks/RunWindFarmSimulation.html#Time-series), it is possible to use time series data as input for a wind farm model. Is it possible to get the flow map at a given time stamp from that?

Best regards

**Comment by madsmpedersen** [comment]
Please use the issue tracker on https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues

see https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues/58
