### ISSUE TITLE
How can I import my own wind farm layout ( CSV file ) on Pywake ?

### ISSUE THREAD

**Issue by Ooussamaa** [DTUWindEnergy/PyWake#9]
Hello,

I am using Pywake. After exploring some of its functionnalities, now I am looking forward to apply them on my own Wind Farm layout, but I can't see what commands/ functions I have to use to do so.

Please push me to the right direction.

Thank you 

Oussama

**Comment by madsmpedersen** [comment]
Please use the issue tracker on https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake/-/issues

**Comment by madsmpedersen** [comment]
If you are considering your own 
- site configuration: https://topfarm.pages.windenergy.dtu.dk/PyWake/notebooks/Site.html
- wind turbine: https://topfarm.pages.windenergy.dtu.dk/PyWake/notebooks/WindTurbines.html
